version: "3.5"

volumes:
  db_next_app:

networks:
  net_next_app:
    driver: bridge

services:
  db_next_app:
    image: postgres:12
    container_name: db_next_app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next_app
    volumes:
      - db_next_app:/var/lib/postgresql/data
    networks:
      - net_next_app
    